const express = require('express');
const fs = require('fs');
const path = require('path');

const app = express();
const port = process.env.PORT || 8080;
const dataDirectory = path.join(__dirname, '..', 'db', 'data');

app.use(express.json());

function parseCsv(fileName) {
  const csv = fs.readFileSync(path.join(dataDirectory, fileName), 'utf8').trim();
  if (!csv) return [];

  // Supports the quoted CSV generated by Export-Csv as well as the original
  // unquoted dummy-data files.
  const parseLine = line => {
    const values = [];
    let value = '';
    let quoted = false;
    for (let index = 0; index < line.length; index += 1) {
      const character = line[index];
      if (character === '"') {
        if (quoted && line[index + 1] === '"') {
          value += '"';
          index += 1;
        } else {
          quoted = !quoted;
        }
      } else if (character === ',' && !quoted) {
        values.push(value);
        value = '';
      } else {
        value += character;
      }
    }
    values.push(value);
    return values;
  };

  const [header, ...lines] = csv.split(/\r?\n/).filter(Boolean).map(parseLine);
  return lines.map(values => Object.fromEntries(header.map((column, index) => [column, values[index] || ''])));
}

const database = {
  PR_Master: parseCsv('pr.reassignment-PR_Master.csv'),
  Approval_Workflow: parseCsv('pr.reassignment-Approval_Workflow.csv'),
  Release_Quotes: parseCsv('pr.reassignment-Release_Quotes.csv'),
  Audit_Log: parseCsv('pr.reassignment-Audit_log.csv')
};

function registeredApprovers() {
  return [...new Set([
    ...database.PR_Master.map(pr => pr.currentApprover),
    ...database.Approval_Workflow.map(workflow => workflow.approverName)
  ].filter(Boolean).map(name => name.trim()))]
    .sort((first, second) => first.localeCompare(second));
}

function registeredDepartments() {
  return [...new Set(database.PR_Master.map(pr => pr.department).filter(Boolean).map(name => name.trim()))]
    .sort((first, second) => first.localeCompare(second));
}

function sendJsonError(response, status, error) {
  return response.status(status).type('application/json').json({ error });
}

// Database API.  Every route returns JSON, including failures, so the UI can
// safely report a useful error instead of attempting to parse an HTML page.
app.get('/api/PR_Master', (_request, response) => response.json({ value: database.PR_Master }));
app.get('/api/Approval_Workflow', (_request, response) => response.json({ value: database.Approval_Workflow }));
app.get('/api/Release_Quotes', (_request, response) => response.json({ value: database.Release_Quotes }));
app.get('/api/Audit_Log', (_request, response) => response.json({ value: database.Audit_Log }));
app.get('/api/approvers', (_request, response) => response.json({ value: registeredApprovers().map(name => ({ name })) }));
app.get('/api/departments', (_request, response) => response.json({ value: registeredDepartments().map(name => ({ name })) }));

app.post('/api/reassignPRs', (request, response) => {
  const { currentApprover, newApprover, status = 'pending', department } = request.body || {};
  const normalized = value => typeof value === 'string' ? value.trim() : '';
  const outgoing = normalized(currentApprover);
  const incoming = normalized(newApprover);
  const selectedDepartment = normalized(department);
  const matchesRegisteredApprover = value => registeredApprovers().some(name => name.toLowerCase() === value.toLowerCase());

  if (!outgoing || !incoming || !selectedDepartment) {
    return sendJsonError(response, 400, 'Current approver, new approver, and SAP department are required.');
  }
  if (!matchesRegisteredApprover(outgoing) || !matchesRegisteredApprover(incoming)) {
    return sendJsonError(response, 400, 'Both approvers must be registered in the PR approval data.');
  }
  if (!registeredDepartments().some(name => name.toLowerCase() === selectedDepartment.toLowerCase())) {
    return sendJsonError(response, 400, 'The selected SAP department is not registered in the PR data.');
  }

  const selectedPRs = database.PR_Master.filter(pr =>
    pr.currentApprover.toLowerCase() === outgoing.toLowerCase() &&
    pr.status.toLowerCase() === normalized(status).toLowerCase() &&
    pr.department.toLowerCase() === selectedDepartment.toLowerCase()
  );
  if (!selectedPRs.length) {
    return response.json({ value: `No matching PRs found for ${outgoing}.` });
  }

  const now = new Date().toISOString();
  const systemUser = request.get('x-sap-user') || 'anonymous';
  const prIds = new Set(selectedPRs.map(pr => pr.ID));
  selectedPRs.forEach(pr => {
    const oldApprover = pr.currentApprover;
    pr.currentApprover = incoming;
    pr.modifiedAt = now;
    pr.modifiedBy = systemUser;
    database.Audit_Log.push({
      ID: `${Date.now()}-${pr.ID}`,
      prNumber: pr.prNumber,
      oldApprover,
      newApprover: incoming,
      createdAt: now,
      createdBy: systemUser,
      modifiedAt: now,
      modifiedBy: systemUser
    });
  });
  database.Approval_Workflow.forEach(workflow => {
    if (prIds.has(workflow.pr_ID) && workflow.approverName.toLowerCase() === outgoing.toLowerCase()) {
      workflow.approverName = incoming;
      workflow.modifiedAt = now;
      workflow.modifiedBy = systemUser;
    }
  });

  return response.json({ value: `Successfully reassigned ${selectedPRs.length} PR(s) in ${selectedDepartment} from "${outgoing}" to "${incoming}".` });
});

// API misses must never fall through to Express's HTML 404 page.
app.use('/api', (_request, response) => sendJsonError(response, 404, 'Route not found'));
app.use(express.static(path.join(__dirname, '..', 'app')));
app.use((_request, response) => response.sendFile(path.join(__dirname, '..', 'app', 'index.html')));
app.use((error, _request, response, _next) => {
  console.error(error);
  sendJsonError(response, 500, 'Internal server error');
});

app.listen(port, () => console.log(`PR reassignment prototype running at http://localhost:${port}`));
